[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
face_swap = "56xKyGcHxr8VPv8mjfyaieMMUymqiEWFqf1tDSoKYcth"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./wallets/phantom-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
